"""Export wah_tour_db to wah_tour_db_complete.sql (schema + data)."""
import os
import sys

import MySQLdb


def load_env(env_path):
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip()] = val.strip()


def sql_escape(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bool):
        return "1" if value else "0"
    s = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def export():
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    load_env(os.path.join(project_root, ".env"))

    db_name = os.environ.get("DB_NAME", "wah_tour_db")
    db_user = os.environ.get("DB_USER", "root")
    db_pass = os.environ.get("DB_PASSWORD", "")
    db_host = os.environ.get("DB_HOST", "127.0.0.1")
    db_port = int(os.environ.get("DB_PORT", "3306"))

    out_path = os.path.join(os.path.dirname(__file__), "wah_tour_db_complete.sql")

    conn = MySQLdb.connect(
        host=db_host,
        user=db_user,
        passwd=db_pass,
        port=db_port,
        charset="utf8mb4",
    )
    cur = conn.cursor()

    lines = [
        "-- Wah Cantt Coaster Tour - Complete MySQL Database",
        "-- Generated by database/export_db.py",
        f"-- Database: {db_name}",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
        f"CREATE DATABASE IF NOT EXISTS `{db_name}`",
        "  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
        f"USE `{db_name}`;",
        "",
    ]

    cur.execute(f"USE `{db_name}`")
    cur.execute("SHOW TABLES")
    tables = [row[0] for row in cur.fetchall()]

    for table in tables:
        cur.execute(f"SHOW CREATE TABLE `{table}`")
        create_sql = cur.fetchone()[1]
        lines.append(f"DROP TABLE IF EXISTS `{table}`;")
        lines.append(f"{create_sql};")
        lines.append("")

    for table in tables:
        cur.execute(f"SELECT * FROM `{table}`")
        rows = cur.fetchall()
        if not rows:
            continue
        cur.execute(f"SHOW COLUMNS FROM `{table}`")
        columns = [col[0] for col in cur.fetchall()]
        col_list = ", ".join(f"`{c}`" for c in columns)
        lines.append(f"-- Data for `{table}`")
        for row in rows:
            values = ", ".join(sql_escape(v) for v in row)
            lines.append(f"INSERT INTO `{table}` ({col_list}) VALUES ({values});")
        lines.append("")

    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    cur.close()
    conn.close()
    print(f"Exported {len(tables)} tables to {out_path}")
    return True


if __name__ == "__main__":
    sys.exit(0 if export() else 1)
